<?php

namespace ContainerEjvUsEi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VdEoghzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VdEoghz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VdEoghz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ClientController::register' => ['privates', '.service_locator.LHzXW9X.App\\Controller\\ClientController::register()', 'getClientControllerregisterService', true],
            'App\\Controller\\ClientController::list' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ClientController::list()', 'getClientControllerlistService', true],
            'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.LHzXW9X.App\\Controller\\ClientController::edit()', 'getClientControllereditService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.0jUX5FG.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ClientController:register' => ['privates', '.service_locator.LHzXW9X.App\\Controller\\ClientController::register()', 'getClientControllerregisterService', true],
            'App\\Controller\\ClientController:list' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\ClientController::list()', 'getClientControllerlistService', true],
            'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.LHzXW9X.App\\Controller\\ClientController::edit()', 'getClientControllereditService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.0jUX5FG.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ClientController::register' => '?',
            'App\\Controller\\ClientController::list' => '?',
            'App\\Controller\\ClientController::edit' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ClientController:register' => '?',
            'App\\Controller\\ClientController:list' => '?',
            'App\\Controller\\ClientController:edit' => '?',
            'App\\Controller\\ClientController:show' => '?',
        ]);
    }
}
