<?php

namespace ContainerEjvUsEi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LHzXW9XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LHzXW9X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LHzXW9X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'scoringService' => ['privates', 'App\\Service\\ScoringService', 'getScoringServiceService', true],
        ], [
            'doctrine' => '?',
            'scoringService' => 'App\\Service\\ScoringService',
        ]);
    }
}
