<?php

namespace ContainerLx5e6ax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LHzXW9X.App\Controller\ClientController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LHzXW9X.App\\Controller\\ClientController::register()'] = ($container->privates['.service_locator.LHzXW9X'] ?? $container->load('get_ServiceLocator_LHzXW9XService'))->withContext('App\\Controller\\ClientController::register()', $container);
    }
}
