<?php

namespace ContainerLx5e6ax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecalculateScoringCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\RecalculateScoringCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\RecalculateScoringCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:recalculate-scoring', [], 'Рассчитывает скоринг клиентов (одного или всех)', false, #[\Closure(name: 'App\\Command\\RecalculateScoringCommand')] fn (): \App\Command\RecalculateScoringCommand => ($container->privates['App\\Command\\RecalculateScoringCommand'] ?? $container->load('getRecalculateScoringCommandService')));
    }
}
