<?php

namespace ContainerLx5e6ax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecalculateScoringCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RecalculateScoringCommand' shared autowired service.
     *
     * @return \App\Command\RecalculateScoringCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/RecalculateScoringCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ScoringService.php';

        $container->privates['App\\Command\\RecalculateScoringCommand'] = $instance = new \App\Command\RecalculateScoringCommand(($container->privates['App\\Service\\ScoringService'] ??= new \App\Service\ScoringService()), ($container->privates['App\\Repository\\ClientRepository'] ?? $container->load('getClientRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:recalculate-scoring');
        $instance->setDescription('Рассчитывает скоринг клиентов (одного или всех)');

        return $instance;
    }
}
