<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLx5e6ax\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLx5e6ax/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLx5e6ax.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLx5e6ax\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLx5e6ax\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lx5e6ax',
    'container.build_id' => '3747d882',
    'container.build_time' => 1745737865,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLx5e6ax');
